"""Add photo field

Revision ID: d2a05477ee36
Revises: e406eed0b97d
Create Date: 2022-09-13 22:13:05.360612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a05477ee36'
down_revision = 'e406eed0b97d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
